#ingress with LB
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maps-ingress
  namespace: maps
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "maps-public-ip"
spec:
  tls:
  - secretName: ssl-certs
  backend:
    # Re-use kong-proxy as the default backend so we stay under the default
    # quota for gce BackendServices.
    serviceName: nominatim
    servicePort: 80
  rules:
  - host: maps.twenty.co
    http:
      paths:
      - path: /*
        backend:
          serviceName: nominatim
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nominatim
  namespace: maps
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: nominatim
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nominatim
  namespace: maps
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nominatim
        track: stable
    spec:
      affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - nominatim
                topologyKey: kubernetes.io/hostname
      volumes:
      - name: nominatim-secret-volume
        secret:
          secretName: nominatim-storage-secret
      containers:
      - name: nominatim-k8s
        image: us.gcr.io/is-pipeline/nominatim:2.3-custom
        env:
        - name: NOMINATIM_MODE
          value: RESTORE
        - name: NOMINATIM_DATA_LABEL
          value: maldives-20161213
        - name: NOMINATIM_SA_KEY_PATH
          value: "/etc/nominatim-secret-volume/service-account-key.json"
        - name: NOMINATIM_PROJECT_ID
          value: is-pipeline
        - name: NOMINATIM_GS_BUCKET
          value: "gs://twenty-maps"
        volumeMounts:
        - name: nominatim-secret-volume
          readOnly: true
          mountPath: /etc/nominatim-secret-volume
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /search
            port: 8080
          initialDelaySeconds: 2500
          timeoutSeconds: 10